### ISSUE TITLE
The Program is not really applying

### ISSUE THREAD

**Issue by itzkou** [nicolomantini/LinkedIn-Easy-Apply-Bot#11]
Usually when I apply for a job on LinkedIn I receive an email that confirms my application,but I didn't receive any email .So I went to linkedIn to reapply for the same job that the bot should 've applied to ,normally I can't apply to it anymore since the bot has already did but in fact I had to apply for it manually so the bot is not working correctly.
![image](https://user-images.githubusercontent.com/56657738/70749162-ea4dfc00-1d2b-11ea-9788-35533297906d.png)

**Comment by krapes** [comment]
Hey @ronnieotieno,

I've fixed the errors so that it now applies to job. Before as you mentioned, it did not know how to handle the new button structure of "Next", "Review", "Submit".

I submitted a pull request to this repo [Here](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/pull/19)

Or you can download it from 
https://github.com/krapes/LinkedIn-Easy-Apply-Bot.git

**Comment by ronnieotieno** [comment]
Hey there, thanks it works only one problem. It crashes when it countered
Chinese or any other characters.

**Comment by alijnmerchant21** [comment]
@krapes I'm still facing the same issue. Even though it encounters 'Easy Apply' it just skips it. Also, I did receive any confirmation via email - which indicates job was never applied. Please help.!
